name: Deploy to OCI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.API_KEY }}

      - name: Deploy to OCI
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@129.154.53.45 '
            ssh -o StrictHostKeyChecking=no fastapi "
              cd ~/jobAPI &&
              git pull &&

              # 기존 컨테이너 중지 및 삭제
              docker stop fastapi || true &&
              docker rm fastapi || true &&

              # 이미지 빌드
              docker build -t fastapi-app . &&

              # 컨테이너 실행
              docker run -d -p 8000:8000 \
                -e OPENAI=${{ secrets.OPENAI_KEY }} \
                --name fastapi fastapi-app
            "
          '
